before:
  hooks:
    - go mod download
builds:
  - id: petra
    binary: petra
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: petractl
    binary: petractl
    main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto

dockers:
  -
    image_templates:
    - "europe-docker.pkg.dev/orga-automation-58dl/utils/{{ .ProjectName }}:latest"
    - "europe-docker.pkg.dev/orga-automation-58dl/utils/{{ .ProjectName }}:{{ .Summary }}"
    - "europe-docker.pkg.dev/orga-automation-58dl/utils/{{ .ProjectName }}:v{{ .Major }}"
    - "europe-docker.pkg.dev/orga-automation-58dl/utils/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"