apiVersion: v1
kind: Service
metadata:
  name: petra-service
spec:
  type: LoadBalancer
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: petra
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000