project_name: petractl

before:
  hooks:
    - go mod download
builds:
  - id: petractl
    binary: petractl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto