before:
  hooks:
    - go mod download
builds:
  - id: petra
    binary: petra
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
release:
  # don't publish new release for petra server
  # only for petractl
  disable: true

dockers:
  -
    image_templates:
    - "ghcr.io/devoteamgcloud/{{ .ProjectName }}:latest"
    - "ghcr.io/devoteamgcloud/{{ .ProjectName }}:{{ .Major }}"
    - "ghcr.io/devoteamgcloud/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/devoteamgcloud/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    - "europe-west1-docker.pkg.dev/dgc-petra-registry-512a/dgc-registry/{{ .ProjectName }}:latest"
    - "europe-west1-docker.pkg.dev/dgc-petra-registry-512a/dgc-registry/{{ .ProjectName }}:{{ .Major }}"
    - "europe-west1-docker.pkg.dev/dgc-petra-registry-512a/dgc-registry/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "europe-west1-docker.pkg.dev/dgc-petra-registry-512a/dgc-registry/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
