auth:
  username: rabbittibbar
  password: buZZGJoWYPn9
  erlangCookie: FAv4q4smHsQAYqbIiSiiSJ4dRS6JXKet

plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s rabbitmq_shovel rabbitmq_shovel_management rabbitmq_top"

replicaCount: 3

podLabels:
  disable-injection: "true"

podAnnotations:
  sidecar.istio.io/proxyCPU: "200m"
  sidecar.istio.io/proxyMemory: "256Mi"
  sidecar.istio.io/proxyCPULimit: "200m"
  sidecar.istio.io/proxyMemoryLimit: "256Mi"

persistence:
  size: 100Gi
  storageClass: ssd

metrics:
  enabled: true
  disabled_aggregation: true

resources:
  requests:
    memory: 24Gi
    cpu: 6000m
  limits:
    memory: 24Gi
    cpu: 6000m

memoryHighWatermark:
  enabled: true
  type: "relative"
  value: 0.4

networkPolicy:
  enabled: false
  allowExternal: false

pdb:
  create: true
  minAvailable: 2

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: sarenza.com/lifecycle
              operator: In
              values:
                - persistent
            - key: sarenza.com/dedicated
              operator: In
              values:
                - rabbitmq
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: "kubernetes.io/hostname"
      labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
              - rabbitmq
