name: Create and Publish Petra docker image (CLI and Server)

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      go-version:
        required: true
        type: string
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        description: "Google application credentials"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ${{inputs.working-directory}}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.go-version}}
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json:  '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build
        run: make ci

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.*

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}

  tests-and-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{inputs.working-directory}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.go-version}}

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json:  '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Run tests
        run: make test

      - name: Release test
        run: make build

  goreleaser:
    // make release on main branch only
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{inputs.working-directory}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.go-version}}

      - name: "Docker login"
        run: docker login docker.pkg.github.com -u docker -p ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}