name: Create and Publish Petra docker image (CLI and Server)

env:
    # GOOGLE_APPLICATION_CREDENTIALS: key.json

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      go-version:
        required: true
        type: string

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ${{inputs.working-directory}}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.go-version}}

      - name: Build
        run: make ci
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.*

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}

  release-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{inputs.working-directory}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.go-version}}

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      # - uses: actions/checkout@v3
      # - uses: google-github-actions/setup-gcloud@main
      #   with:
      #     version: '270.0.0'
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      # - run: echo -n ${{ secrets.GCP_SA_KEY }} > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Run tests
        run: make test

      - name: Release test
        run: make build