name: doc
on:
  push:
    branches:
      - "main"
      - "doc/readme"

jobs:

  update-documentation:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: petractl-build
        run: go build && echo "$PWD" >> $GITHUB_PATH
        working-directory: petractl

      - uses: charmbracelet/vhs-action@v1
        with:
          path: 'petractl.tape'
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          file_pattern: '*.gif'