name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - "*"
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci-petra:
    name: lint-petra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint-petra
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          only-new-issues: true
  golangci-petractl:
    name: lint-petractl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint-petractl
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          working-directory: petractl