name: qa
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  petra-qa:
    name: petra-qa
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1
      - uses: actions/checkout@v3
      - name: go-build
        run: go build

  petractl-qa: 
    name: petractl-qa
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1
      - uses: actions/checkout@v3
      - name: go-build
        run: go build
        working-directory: petractl